import type { Metadata } from "next";
import { ContextProvider } from "./libs/services/context/ContextProvider";
import QueryProvider from "./libs/QueryProvider";
import LayoutDimensions from "@/components/LayoutDimensions";
import { AuthManagerProvider } from "./auth/context/AuthManager";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <QueryProvider>
            <AuthManagerProvider>
              <LayoutDimensions>
                <Header />
                {children}
              </LayoutDimensions>
            </AuthManagerProvider>
          </QueryProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
